# Generated by Django 2.1.7 on 2019-05-24 02:35

import comment_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=626, null=True, verbose_name='Title')),
                ('data', models.TextField(blank=True, default='', help_text='Markdown content.', null=True, verbose_name='Data')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('html', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentFileWrapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='')),
            ],
            bases=(comment_app.models.CommentFileWrapperMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CommentSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(blank=True, default='', max_length=255)),
                ('done', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
