# Generated by Django 2.1.7 on 2019-05-31 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_app', '0002_auto_20190531_0119'),
        ('comment_app', '0002_eattachcommentfile_ecreatecomment_edeletecomment_edettachcommentfile_erestorecomment_eupdatecomment'),
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eupdatecomment',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post_app.Post'),
        ),
        migrations.AddField(
            model_name='eupdatecomment',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comment_app.Comment'),
        ),
        migrations.AddField(
            model_name='erestorecomment',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_restore_comment1', to='comment_app.Comment'),
        ),
        migrations.AddField(
            model_name='erestorecomment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_restore_comment0', to='post_app.Post'),
        ),
        migrations.AddField(
            model_name='edettachcommentfile',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_dettach_comment_file1', to='comment_app.Comment'),
        ),
        migrations.AddField(
            model_name='edeletecomment',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post_app.Post'),
        ),
        migrations.AddField(
            model_name='ecreatecomment',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post_app.Post'),
        ),
        migrations.AddField(
            model_name='ecreatecomment',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comment_app.Comment'),
        ),
        migrations.AddField(
            model_name='eattachcommentfile',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_attach_comment_file1', to='comment_app.Comment'),
        ),
        migrations.AddField(
            model_name='eattachcommentfile',
            name='filewrapper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_attach_comment_file0', to='comment_app.CommentFileWrapper'),
        ),
        migrations.AddField(
            model_name='commentsearch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.Organization'),
        ),
        migrations.AddField(
            model_name='commentsearch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.User'),
        ),
        migrations.AddField(
            model_name='commentfilewrapper',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment_app.Comment'),
        ),
        migrations.AddField(
            model_name='commentfilewrapper',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.Organization'),
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_app.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post_app.Post'),
        ),
        migrations.AlterUniqueTogether(
            name='commentsearch',
            unique_together={('user', 'organization')},
        ),
    ]
