#!/usr/bin/env python

import os
import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "arcamens.settings")
django.setup()

# your imports, e.g. Django models
from django.contrib.auth.models import User
User.objects.create_superuser('arcamens', 'developer@arcamens.com', 'arcamens')


