#!/usr/bin/env python
import os
import django
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "arcamens.settings")
django.setup()

from core_app.models import Event
events = Event.objects.all()

for ind in events:
    ind.signers.add(ind.users.all())
    ind.users.clear()

