# Generated by Django 2.1.7 on 2019-05-24 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group_app', '0001_initial'),
        ('core_app', '0003_auto_20190524_0235'),
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epastepost',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='e_paste_post1', to='post_app.Post'),
        ),
        migrations.AddField(
            model_name='ecreategroup',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_create_group', to='group_app.Group'),
        ),
        migrations.AddField(
            model_name='ebindgroupuser',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_bind_group_user', to='group_app.Group'),
        ),
        migrations.AddField(
            model_name='ebindgroupuser',
            name='peer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_app.User'),
        ),
        migrations.AlterUniqueTogether(
            name='groupship',
            unique_together={('group', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='grouppin',
            unique_together={('user', 'organization', 'group')},
        ),
    ]
