# Generated by Django 2.1.7 on 2019-05-24 02:35

import card_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('expired', models.BooleanField(blank=True, db_index=True, default=False)),
                ('label', models.CharField(help_text='Label, Deadline, ...', max_length=626, null=True, verbose_name='Label')),
                ('priority', models.IntegerField(default=0)),
                ('data', models.TextField(blank=True, default='', help_text='Markdown content.', verbose_name='Data')),
                ('done', models.BooleanField(blank=True, default=False)),
                ('html', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardClipboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CardFileWrapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='')),
            ],
            bases=(card_app.models.CardFileWrapperMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CardFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(blank=True, default='', help_text='Example: owner:oliveira  + tag:bug', max_length=255)),
                ('status', models.BooleanField(blank=True, default=False, help_text='Filter On/Off.')),
            ],
        ),
        migrations.CreateModel(
            name='CardPinMixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CardSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(blank=True, default='', help_text='tag:issue + owner:iury', max_length=255)),
                ('done', models.BooleanField(blank=True, default=False)),
                ('assigned', models.BooleanField(default=True)),
                ('assigned_by_me', models.BooleanField(default=True)),
                ('assigned_to_me', models.BooleanField(blank=True, default=True)),
                ('created_by_me', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CardTagship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardTaskship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(blank=True, max_length=626, null=True)),
            ],
        ),
    ]
