# Generated by Django 2.1.7 on 2019-05-24 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('list_app', '0001_initial'),
        ('card_app', '0001_initial'),
        ('core_app', '0001_initial'),
        ('board_app', '0002_auto_20190524_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='EArchiveCard',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.Event')),
                ('ancestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_archive_card0', to='list_app.List')),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_archive_card2', to='board_app.Board')),
                ('cards', models.ManyToManyField(related_name='e_archive_card1', to='card_app.Card')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_app.event',),
        ),
        migrations.CreateModel(
            name='EArrivedCardDeadline',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.Event')),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('ancestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_arrived_card_deadline0', to='list_app.List')),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_arrived_card_deadline0', to='board_app.Board')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_arrived_card_deadline0', to='card_app.Card')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_app.event',),
        ),
        migrations.CreateModel(
            name='EAttachCardFile',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.Event')),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_attach_card_file3', to='board_app.Board')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_attach_card_file1', to='card_app.Card')),
                ('filewrapper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_attach_card_file0', to='card_app.CardFileWrapper')),
                ('list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_attach_card_file2', to='list_app.List')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_app.event',),
        ),
        migrations.CreateModel(
            name='EBindCardWorker',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.Event')),
                ('status', models.CharField(max_length=626, null=True)),
                ('ancestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_bind_card_worker0', to='list_app.List')),
                ('board', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_bind_card_worker3', to='board_app.Board')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_bind_card_worker1', to='card_app.Card')),
                ('peer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_bind_card_worker2', to='core_app.User')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_app.event',),
        ),
        migrations.CreateModel(
            name='EBindTagCard',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.Event')),
                ('ancestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_bind_tag_card0', to='list_app.List')),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_bind_tag_card3', to='board_app.Board')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_bind_tag_card1', to='card_app.Card')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_bind_tag_card2', to='core_app.Tag')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_app.event',),
        ),
        migrations.CreateModel(
            name='ECopyCard',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.Event')),
                ('ancestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_copy_card0', to='list_app.List')),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_copy_card2', to='board_app.Board')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_copy_card1', to='card_app.Card')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_app.event',),
        ),
        migrations.CreateModel(
            name='ECreateCard',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.Event')),
                ('ancestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_create_card0', to='list_app.List')),
                ('board', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_create_card2', to='board_app.Board')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_create_card1', to='card_app.Card')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_app.event',),
        ),
        migrations.CreateModel(
            name='ECreateFork',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.Event')),
                ('ancestor0', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_create_fork0', to='list_app.List')),
                ('ancestor1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_create_fork5', to='list_app.List')),
                ('board0', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_create_fork3', to='board_app.Board')),
                ('board1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_create_fork4', to='board_app.Board')),
                ('card0', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_create_fork1', to='card_app.Card')),
                ('card1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_create_fork2', to='card_app.Card')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_app.event',),
        ),
        migrations.CreateModel(
            name='ECutCard',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.Event')),
                ('ancestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_cut_card0', to='list_app.List')),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_cut_card2', to='board_app.Board')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_cut_card1', to='card_app.Card')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_app.event',),
        ),
        migrations.CreateModel(
            name='EDeleteCard',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.Event')),
                ('label', models.CharField(max_length=626, null=True)),
                ('ancestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_delete_card0', to='list_app.List')),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_delete_card1', to='board_app.Board')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_app.event',),
        ),
        migrations.CreateModel(
            name='EDettachCardFile',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.Event')),
                ('filename', models.CharField(max_length=626, null=True)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_dettach_card_file3', to='board_app.Board')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_dettach_card_file1', to='card_app.Card')),
                ('list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_dettach_card_file2', to='list_app.List')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_app.event',),
        ),
        migrations.CreateModel(
            name='ERelateCard',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.Event')),
                ('ancestor0', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_relate_card0', to='list_app.List')),
                ('ancestor1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_relate_card1', to='list_app.List')),
                ('board0', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_relate_card4', to='board_app.Board')),
                ('board1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_relate_card5', to='board_app.Board')),
                ('card0', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_relate_card2', to='card_app.Card')),
                ('card1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_relate_card3', to='card_app.Card')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_app.event',),
        ),
        migrations.CreateModel(
            name='ERestoreCard',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.Event')),
                ('event_html', models.TextField(blank=True, null=True)),
                ('ancestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_restore_card0', to='list_app.List')),
                ('board', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_restore_card2', to='board_app.Board')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_restore_card1', to='card_app.Card')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_app.event',),
        ),
        migrations.CreateModel(
            name='ESetCardDeadline',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.Event')),
                ('ancestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_set_card_deadline0', to='list_app.List')),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_set_card_deadline2', to='board_app.Board')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_set_card_deadline1', to='card_app.Card')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_app.event',),
        ),
        migrations.CreateModel(
            name='ESetCardPriorityDown',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.Event')),
                ('ancestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_set_card_priority_down0', to='list_app.List')),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_set_card_priority_down3', to='board_app.Board')),
                ('card0', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_set_card_priority_down1', to='card_app.Card')),
                ('card1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_set_card_priority_down2', to='card_app.Card')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_app.event',),
        ),
        migrations.CreateModel(
            name='ESetCardPriorityUp',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.Event')),
                ('ancestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_set_card_priority_up0', to='list_app.List')),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_set_card_priority_up3', to='board_app.Board')),
                ('card0', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_set_card_priority_up1', to='card_app.Card')),
                ('card1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_set_card_priority_up2', to='card_app.Card')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_app.event',),
        ),
        migrations.CreateModel(
            name='EUnarchiveCard',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.Event')),
                ('ancestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_unarchive_card0', to='list_app.List')),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_unarchive_card2', to='board_app.Board')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_unarchive_card1', to='card_app.Card')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_app.event',),
        ),
        migrations.CreateModel(
            name='EUnbindCardWorker',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.Event')),
                ('ancestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_unbind_card_worker0', to='list_app.List')),
                ('board', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_unbind_card_worker3', to='board_app.Board')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_unbind_card_worker1', to='card_app.Card')),
                ('peer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_unbind_card_worker2', to='core_app.User')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_app.event',),
        ),
        migrations.CreateModel(
            name='EUnbindTagCard',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.Event')),
                ('ancestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_unbind_tag_card0', to='list_app.List')),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_unbind_tag_card3', to='board_app.Board')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_unbind_tag_card1', to='card_app.Card')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_unbind_tag_card2', to='core_app.Tag')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_app.event',),
        ),
        migrations.CreateModel(
            name='EUnrelateCard',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.Event')),
                ('ancestor0', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_unrelate_card0', to='list_app.List')),
                ('ancestor1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_unrelate_card1', to='list_app.List')),
                ('board0', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_unrelate_card4', to='board_app.Board')),
                ('board1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_unrelate_card5', to='board_app.Board')),
                ('card0', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_unrelate_card2', to='card_app.Card')),
                ('card1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_unrelate_card3', to='card_app.Card')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_app.event',),
        ),
        migrations.CreateModel(
            name='EUpdateCard',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.Event')),
                ('card_label', models.CharField(help_text='Label, Deadline, ...', max_length=626, null=True, verbose_name='Label')),
                ('card_html', models.TextField(blank=True, null=True)),
                ('card_data', models.TextField(blank=True, default='', help_text='Markdown content.', verbose_name='Data')),
                ('ancestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_update_card0', to='list_app.List')),
                ('board', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_update_card2', to='board_app.Board')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_update_card1', to='card_app.Card')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_app.event',),
        ),
        migrations.CreateModel(
            name='CardPin',
            fields=[
                ('cardpinmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='card_app.CardPinMixin')),
            ],
            bases=('card_app.cardpinmixin',),
        ),
        migrations.AddField(
            model_name='cardtaskship',
            name='assigner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_assingership', to='core_app.User'),
        ),
        migrations.AddField(
            model_name='cardtaskship',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='card_app.Card'),
        ),
        migrations.AddField(
            model_name='cardtaskship',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_workership', to='core_app.User'),
        ),
        migrations.AddField(
            model_name='cardtagship',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='card_app.Card'),
        ),
        migrations.AddField(
            model_name='cardtagship',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_tagship', to='core_app.Tag'),
        ),
        migrations.AddField(
            model_name='cardtagship',
            name='tagger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_taggership', to='core_app.User'),
        ),
        migrations.AddField(
            model_name='cardsearch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.Organization'),
        ),
        migrations.AddField(
            model_name='cardsearch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.User'),
        ),
        migrations.AddField(
            model_name='cardfilter',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_filter', to='list_app.List'),
        ),
        migrations.AddField(
            model_name='cardfilter',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.Organization'),
        ),
        migrations.AddField(
            model_name='cardfilter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.User'),
        ),
        migrations.AddField(
            model_name='cardfilewrapper',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='card_app.Card'),
        ),
        migrations.AddField(
            model_name='cardfilewrapper',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.Organization'),
        ),
        migrations.AddField(
            model_name='cardclipboard',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selected', to='card_app.Card'),
        ),
        migrations.AddField(
            model_name='cardclipboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.User'),
        ),
        migrations.AddField(
            model_name='card',
            name='ancestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='list_app.List'),
        ),
        migrations.AddField(
            model_name='card',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_app.User'),
        ),
        migrations.AddField(
            model_name='card',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forks', to='card_app.Card'),
        ),
    ]
