# Generated by Django 2.1.7 on 2019-06-11 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('note_app', '0001_initial'),
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EGithubCommit',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.Event')),
                ('url', models.CharField(max_length=626, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('core_app.event',),
        ),
        migrations.CreateModel(
            name='GithubHook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', help_text='Example: team/repo_name', max_length=626, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_hooks', to='core_app.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='egithubcommit',
            name='hook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='github_app.GithubHook'),
        ),
        migrations.AddField(
            model_name='egithubcommit',
            name='note',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='github_commits', to='note_app.Note'),
        ),
    ]
