# Generated by Django 2.1.7 on 2019-05-31 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_app', '0001_initial'),
        ('list_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipboard',
            name='lists',
            field=models.ManyToManyField(related_name='list_clipboard_users', to='list_app.List'),
        ),
        migrations.AddField(
            model_name='clipboard',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.Organization'),
        ),
    ]
