# Generated by Django 2.1.7 on 2019-06-11 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post_app', '0001_initial'),
        ('core_app', '0002_auto_20190611_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipboard',
            name='posts',
            field=models.ManyToManyField(related_name='post_clipboard_users', to='post_app.Post'),
        ),
        migrations.AddField(
            model_name='clipboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.User'),
        ),
        migrations.AlterUniqueTogether(
            name='userfilter',
            unique_together={('user', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='nodefilter',
            unique_together={('user', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='eventfilter',
            unique_together={('user', 'organization')},
        ),
        migrations.AddField(
            model_name='eunbindtaguser',
            name='peer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e_unbind_user_tag0', to='core_app.User'),
        ),
        migrations.AddField(
            model_name='eunbindtaguser',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.Tag'),
        ),
        migrations.AddField(
            model_name='eremoveorganizationuser',
            name='peer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e_remove_organization_user0', to='core_app.User'),
        ),
        migrations.AddField(
            model_name='ejoinorganization',
            name='peer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e_join_organization0', to='core_app.User'),
        ),
        migrations.AddField(
            model_name='einviteuser',
            name='peer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e_invite_user0', to='core_app.User'),
        ),
        migrations.AddField(
            model_name='ecreatetag',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e_create_tag1', to='core_app.Tag'),
        ),
        migrations.AddField(
            model_name='ebindtaguser',
            name='peer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e_bind_user_tag0', to='core_app.User'),
        ),
        migrations.AddField(
            model_name='ebindtaguser',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='clipboard',
            unique_together={('user', 'organization')},
        ),
    ]
