#!/usr/bin/env python

"""
Add a given user to all boards/timelines of an organization
and adds the user to the organization too.

Usage:

bind-boards/timelines organization-owner-email user-email

"""

import os
import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "arcamens.settings")
django.setup()

from core_app.models import User, Organization
from board_app.models import Board
from timeline_app.models import Timeline
import sys

organization = Organization.objects.get(owner__email__istartswith=sys.argv[1])
user = User.objects.get(email=sys[1])
user.organizations.add(organization)

boards = Board.objects.filter(organization__name__istartswith=sys.argv[2])

for ind in boards:
   ind.members.add(user)

user = User.objects.get(name__istartswith='iury')
timelines = Timeline.objects.filter(organization__name__istartswith=sys.argv[2])

for ind in timelines:
   ind.users.add(user)
