# Generated by Django 2.1.7 on 2019-05-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Arcamens', max_length=250, null=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='', help_text='Example: /projectname/', max_length=626, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('public', models.BooleanField(blank=True, default=False, help_text='Visible to all organization members.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BoardPin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Boardship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('0', 'Admin'), ('1', 'Member'), ('2', 'Guest')], default='2', max_length=6)),
            ],
        ),
    ]
