# Generated by Django 2.1.7 on 2019-06-11 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board_app', '0001_initial'),
        ('list_app', '0001_initial'),
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EBindBoardUser',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.Event')),
                ('status', models.CharField(choices=[('0', 'Admin'), ('1', 'Member'), ('2', 'Guest')], max_length=6)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_bind_board_user', to='board_app.Board')),
                ('peer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_app.User')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_app.event',),
        ),
        migrations.CreateModel(
            name='ECreateBoard',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.Event')),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_create_board', to='board_app.Board')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_app.event',),
        ),
        migrations.CreateModel(
            name='EDeleteBoard',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.Event')),
                ('board_name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
            bases=('core_app.event',),
        ),
        migrations.CreateModel(
            name='EPasteList',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.Event')),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_paste_list0', to='board_app.Board')),
                ('lists', models.ManyToManyField(blank=True, related_name='e_paste_list1', to='list_app.List')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_app.event',),
        ),
        migrations.CreateModel(
            name='EUnbindBoardUser',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.Event')),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_unbind_board_user', to='board_app.Board')),
                ('peer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_app.User')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_app.event',),
        ),
        migrations.CreateModel(
            name='EUpdateBoard',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.Event')),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_update_board', to='board_app.Board')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_app.event',),
        ),
        migrations.AddField(
            model_name='boardship',
            name='binder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='binder_boardship', to='core_app.User'),
        ),
        migrations.AddField(
            model_name='boardship',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board_app.Board'),
        ),
        migrations.AddField(
            model_name='boardship',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_boardship', to='core_app.User'),
        ),
        migrations.AddField(
            model_name='boardpin',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board_app.Board'),
        ),
        migrations.AddField(
            model_name='boardpin',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_app.Organization'),
        ),
        migrations.AddField(
            model_name='boardpin',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_app.User'),
        ),
        migrations.AddField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='boards', through='board_app.Boardship', to='core_app.User'),
        ),
        migrations.AddField(
            model_name='board',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='core_app.Node'),
        ),
        migrations.AddField(
            model_name='board',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='core_app.Organization'),
        ),
        migrations.AddField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_boards', to='core_app.User'),
        ),
        migrations.AlterUniqueTogether(
            name='boardship',
            unique_together={('board', 'member')},
        ),
        migrations.AlterUniqueTogether(
            name='boardpin',
            unique_together={('user', 'organization', 'board')},
        ),
    ]
