# Generated by Django 2.1.7 on 2019-05-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitbucketHook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', help_text='Example: team/repo_name', max_length=626, null=True)),
            ],
        ),
    ]
