# Generated by Django 2.1.7 on 2019-05-24 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('note_app', '0001_initial'),
        ('bitbucket_app', '0001_initial'),
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EBitbucketCommit',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.Event')),
                ('url', models.CharField(max_length=626, null=True)),
                ('hook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bitbucket_app.BitbucketHook')),
                ('note', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitbucket_commits', to='note_app.Note')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_app.event',),
        ),
        migrations.AddField(
            model_name='bitbuckethook',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitbucket_hooks', to='core_app.Organization'),
        ),
    ]
